better caret styling
joomla/cassiopeia pull request #42
Opened 2020-08-24 16:17 UTC by N6REJ

Pull Request for Issue # .

### Summary of Changes
change to using native BS caret class

### Testing Instructions
apply pr.
Verify caret shows and transforms on click.
verify large gap between caret and menu item word is gone.

### Expected result
![image](https://user-images.githubusercontent.com/1850089/91069445-09ab6180-e5fb-11ea-8769-b98cd6a9be44.png)

### Actual result
![image](https://user-images.githubusercontent.com/1850089/91069705-5c851900-e5fb-11ea-953e-8f05336f0ee2.png)

### Documentation Changes Required

2020-08-24 20:15 UTC, hans2103 commented
Applied the new styling and I notice a shift of a couple of pixels to the right of the aligned menu items when opening the dropdown. 

I would suggest the following changes to your PR
- remove the added `vertical-align: baseline;`
- change `@include caret(down);` into @include caret(up);
- change `@include caret(right);` into @include caret(down);

<img width="299" alt="Schermafbeelding 2020-08-24 om 22 15 21" src="https://user-images.githubusercontent.com/639822/91091756-5c1a6b80-e657-11ea-9ae3-8db76211f5f2.png">
<img width="289" alt="Schermafbeelding 2020-08-24 om 22 15 30" src="https://user-images.githubusercontent.com/639822/91091762-5f155c00-e657-11ea-8aac-32e594ddc73e.png">

2020-08-24 20:16 UTC, hans2103 requested changes
Applied the new styling and I notice a shift of a couple of pixels to the right of the aligned menu items when opening the dropdown. 

I would suggest the following changes to your PR
- remove the added `vertical-align: baseline;`
- change `@include caret(down);` into @include caret(up);
- change `@include caret(right);` into @include caret(down);

<img width="299" alt="Schermafbeelding 2020-08-24 om 22 15 21" src="https://user-images.githubusercontent.com/639822/91091756-5c1a6b80-e657-11ea-9ae3-8db76211f5f2.png">
<img width="289" alt="Schermafbeelding 2020-08-24 om 22 15 30" src="https://user-images.githubusercontent.com/639822/91091762-5f155c00-e657-11ea-8aac-32e594ddc73e.png">

2020-08-24 21:12 UTC, N6REJ commented
@hans2103 lets see what the styling people want then we can adjust it.

2020-08-25 18:45 UTC, hans2103 commented
@helvecio ?

2020-08-26 08:52 UTC, chmst commented
Looks good for me. It is better visible .

2020-08-28 14:09 UTC, richard67 commented
@N6REJ Now the problem is not only that this PR meanwhile has conflicts to the target branch, we also have decided to bring the metismenu (= target branch of this PR) and the one for the HTML structure changes together into a new common branch.

I think it would be the best to close this one and later make a new one for the new [4-0-dev-frontend-metismenu-and-html-structure](https://github.com/joomla/cassiopeia/tree/cassiopeia/4-0-dev-frontend-metismenu-and-html-structure) branch.

But maybe wait with that until I have finished my PR #45 ?

What do you think?

2020-08-28 18:15 UTC, N6REJ commented
yeah, lets close this one.

2020-08-28 18:15 UTC, closed without merging